修复 embed.js 相关的 BUG
pengzhanbo/caniuse-embed pull request #4
Opened 2024-12-06 13:19 UTC by Lruihao

- fix: 调整打包配置，修复 embed.js 打包后和本地都不存在的问题
- perf: 修复本地 embed.js 与数据源不对应的问题，增加可选数据源 data-origin 属性

2024-12-06 14:28 UTC, pengzhanbo commented on src/scripts/embed.ts
> +  const source = new URL(import.meta.url)
这里我不是很推荐使用 `import.meta`，它只适用于 `script type="module"`，即文档给出的代码示例，但如果其他用户使用 非 esm 的方式引入脚本，那么这里会发生错误。

2024-12-06 14:54 UTC, Lruihao commented on src/scripts/embed.ts
> +  const source = new URL(import.meta.url)
我以为只能使用 esm 的方式引入，所以才改成这样，刚刚试了一下确实可以去掉 `type="module"`。

介于原来查找 `'script[src*="caniuse"][src*="/embed.js"]'` 的方式可能存在误判，我再使用 `document.currentScript` 兼容一下怎么样，或者您觉得这里应该怎么处理比较好。

2024-12-06 15:09 UTC, pengzhanbo commented on src/scripts/embed.ts
> +  const source = new URL(import.meta.url)
嗯，用 `new URL(typeof import !== 'undefined' ? import.meta.url : document.currentScript)` 应该可以兼容两种场景。

2024-12-06 15:12 UTC, pengzhanbo commented on src/scripts/embed.ts
> +  const source = new URL(import.meta.url)
这里的 示例代码用 `type="module"` 是因为 ，[script type="module"](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/script#module) 自带延迟内容加载完成后执行，对于将这段代码放在内容的何处没有严格的要求。

2024-12-06 15:51 UTC, Lruihao commented on src/scripts/embed.ts
> +  const source = new URL(import.meta.url)
这一点我再研究一下，实在不行还是恢复原来的 querySelector 查找方式。

2024-12-07 04:16 UTC, Lruihao commented on src/scripts/embed.ts
> +  const source = new URL(import.meta.url)
选择了使用 document.currentScript 和 querySelector 的折中处理。

2024-12-07 08:51 UTC, pengzhanbo requested changes

2024-12-07 08:51 UTC, pengzhanbo commented on astro.config.mjs
> +          addWatchFile(embedSource)
不需要使用 `addWatchFile`， `src` 目录默认就已经被 vite 开发服务监听，使用 `addWatchFile` 会导致每次修改文件 [astro 服务都将重启](https://docs.astro.build/zh-cn/reference/integrations-reference/#addwatchfile-%E9%80%89%E9%A1%B9)。但并不需要这么做，`embed.js`作为一个被外部使用的脚本，其运行环境可以认为是脱离于 `astro/vite` 本身的开发服务的，因为它并不是被入口文件导入的模块。要实现对它的监听热更新，也应该是使用 [`import.meta.hot`](https://cn.vite.dev/guide/api-hmr.html#hmr-api) 实现，通过注入相关代码，在 `accept` 中执行热更新操作，`embed.js`的代码内容决定了，最简单的方法就是执行 `localtion.reload()`，也就是刷新页面，否则就需要清除副作用和重新执行。
而手动刷新页面就能解决，因此我也没有在这里注入热更新代码。

2024-12-07 08:54 UTC, Lruihao commented on astro.config.mjs
> +          addWatchFile(embedSource)
好吧

2024-12-07 09:04 UTC, Lruihao commented on astro.config.mjs
> +          addWatchFile(embedSource)
我刚刚试了一下刷新页面不能刷新 embed.js，目前只能重启服务来解决。不过这个不太重要，我先复原了。

2024-12-07 09:30 UTC, pengzhanbo approved these changes

2024-12-07 09:32 UTC, merged

2024-12-08 15:59 UTC, pengzhanbo commented
@Lruihao 我花了些时间查看了为什么刷新没有获得 embed.js 的最新内容，在 astro 中有一套独立于 vite 的 内容缓存策略，在 vite 插件的 load -> transform 生成对应的资源内容后，astro 基于路由映射对内容进行了缓存，在后续的所有请求中，实际上全部都命中了 astro 的缓存，并没有进入到 vite 的 load 钩子中。这导致了源内容发生变更但不生效的问题。（这里我没有从文档中找到如何刷新 astro 缓存的方法， 或许这里 astro 还对 vite 的虚拟文件做了区别，但 `/embed.js` 的路径很明显不会被认为是 虚拟文件）。
这里有其他的方案可以解决，一个是使用 astro 的 api 端点，另一个是使用中间件进行解决。
api 端点会直接影响到生发时和构建时的产物，因此我选择了在开发时使用 vite 开发服务中间件的方式来解决这个问题。

2024-12-09 02:22 UTC, Lruihao commented
@pengzhanbo api 端点会影响到开发时和构建时的产物，包括这个 PR 合并时的配置也是会影响开发时的产物，所以使用中间件的方式解决应该是更好的选择，我拉了最新的代码，目前来看一切正常。